"""Type stubs for the native ThinkingRoot extension module."""

from typing import Any, Optional

class ThinkingRootError(Exception): ...

def compile(path: str) -> dict[str, Any]: ...
def parse_directory(path: str) -> list[dict[str, Any]]: ...
def parse_file(path: str) -> dict[str, Any]: ...
def open(path: str) -> Engine: ...

class Engine:
    def get_entities(self) -> list[dict[str, Any]]: ...
    def get_entity(self, name: str) -> dict[str, Any]: ...
    def get_claims(
        self,
        type: Optional[str] = None,
        min_confidence: Optional[float] = None,
    ) -> list[dict[str, Any]]: ...
    def get_relations(self, entity: str) -> list[dict[str, Any]]: ...
    def get_all_relations(self) -> list[dict[str, Any]]: ...
    def search(self, query: str, top_k: Optional[int] = None) -> dict[str, Any]: ...
    def health(self) -> dict[str, Any]: ...
    def verify(self) -> dict[str, Any]: ...
    def get_sources(self) -> list[dict[str, Any]]: ...
    def get_contradictions(self) -> dict[str, Any]: ...
